apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-app.fullname" . }}
spec:
  selector:
    app: {{ include "django-app.name" . }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
